package zombis;


import java.util.Random;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.JButton;
/**
 *
 * @author gmora
 */
public class Tablero extends javax.swing.JFrame {
  
  //Zombi3 zombi3 = new Zombi3();
  Boton [][] botones =new Boton[7][7];
  int filas=7;
  int columnas=7;
  int i=0;
    public Tablero() {
            initComponents();
            botones();
            base();
            spawn(randInt(0,7),randInt2(0,7));
            obstaculo();
            zombi1();
            zombi2();
            zombi3();
            Perso1();
            Perso2();
            Perso3();
            mover();
            //move();
           
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        disparar = new javax.swing.JButton();
        mover = new javax.swing.JButton();
        trepar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        disparar.setText("Disparar");

        mover.setText("Move");

        trepar.setText("Trepar");
        trepar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treparActionPerformed(evt);
            }
        });

        jButton4.setText("X");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(982, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(disparar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(trepar, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(92, 92, 92))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(trepar, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(disparar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mover, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(977, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 58, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void treparActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tablero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Tablero().setVisible(true);
            }
        });
    }
public void botones(){
    for (int i=0;i<filas;i++){
        for(int j=0;j<columnas;j++){
        botones[i][j]=new Boton(97*j,97*i,100,100);
        botones[i][j].CambiarNombre(i,j);
        jPanel1.add(botones[i][j]);
        
        }
    }
}
public void base(){
    botones[0][2].setBackground(Color.ORANGE);
    botones[0][3].setBackground(Color.ORANGE);
    botones[0][4].setBackground(Color.ORANGE);
    botones[1][2].setBackground(Color.ORANGE);
    botones[1][3].setBackground(Color.ORANGE);
    botones[1][4].setBackground(Color.ORANGE);
    botones[1][2].Cambiar("BASE");
    botones[1][3].Cambiar("BASE");
    botones[1][4].Cambiar("BASE");
    
}
public int randInt(int min, int max) {
    Random rand = new Random();
    int n1 = rand.nextInt(7);
    return n1;
}
public int randInt2(int min, int max){
    Random rand = new Random();
    int n2 = rand.nextInt(7);
    System.out.println(n2);
    return n2;
}

public int spawn(int a,int b){
    botones[6][2].setBackground(Color.WHITE);
    botones[6][3].setBackground(Color.WHITE);
    botones[6][4].setBackground(Color.WHITE);
    a=randInt(0,7);
    b=randInt2(0,7);
    
    if (botones[0][2]==botones[a][b]||botones[0][3]==botones[a][b]||botones[0][4]==botones[a][b]|| botones[1][2]==botones[a][b]||botones[1][3]==botones[a][b]||botones[1][4]==botones[a][b]){
        a=randInt(0,7);
        b=randInt2(0,7);
        return spawn(a,b);
    }
    else{
        botones[a][b].setBackground(Color.WHITE);
    }
   return 0;
   
}

public void end(int a, int b){
    if(botones[0][2]==botones[a][b]||botones[0][3]==botones[a][b]||botones[0][4]==botones[a][b]|| botones[1][2]==botones[a][b]||botones[1][3]==botones[a][b]||botones[1][4]==botones[a][b]){
        System.out.println("Juego Terminado ");
    }
        
}
public void obstaculo(){
    botones[3][1].setBackground(Color.GREEN);
    botones[5][1].setBackground(Color.GREEN);
    botones[3][5].setBackground(Color.GREEN);
    botones[5][5].setBackground(Color.GREEN);
    botones[3][1].Cambiar("Obstaculo");
    botones[5][1].Cambiar("Obstaculo");
    botones[3][5].Cambiar("Obstaculo");
    botones[5][5].Cambiar("Obstaculo");
    
    }


public Boton zombi1(){
        Zombi1 zombi1 = new Zombi1(0,0,false,0,0 );
        botones[6][2].Cambiar("Zombie1");
        int vida = zombi1.vida;
        int dano = zombi1.dano;
        boolean ruido = zombi1.ruido;
        int vision = zombi1.vision;
        int doble_vida=zombi1.getdoble();
        return botones[6][2];
        
}
public void zombi2(){
     Zombis2 zombi2 = new Zombis2(0,0,false,0,0 );
        botones[6][3].Cambiar("Zombie2");
        int vida = zombi2.vida;
        int dano = zombi2.dano;
        boolean ruido = zombi2.ruido;
        int vision = zombi2.vision;
        boolean doble_Acc=zombi2.getAcc();
}

public void zombi3(){
     Zombi3 zombi3 = new Zombi3(0,0,false,0,0 );
        botones[6][4].Cambiar("Zombie3");
        int vida = zombi3.vida;
        int dano = zombi3.dano;
        boolean ruido = zombi3.ruido;
        int vision = zombi3.vision;
        int doble_Vis=zombi3.Getvision();
}
public void Perso1(){
     Personaje1 perso1 = new Personaje1(0,0,0,0,0,0,false,0);
        botones[0][2].Cambiar("Personaje 1");
        int vida = perso1.getVida();
        int ataque = perso1.getAtaque();
        int nivel = perso1.getNivel();
        int vision = perso1.getVision();
        int movimiento=perso1.getRango_mov();
        boolean escalar = perso1.getescalar();
        int may_rang_ataq=perso1.getRango();

}
public void Perso2(){
     Peronsaje2 perso2 = new Peronsaje2(0,0,0,0,0,false,false,0);
        botones[0][3].Cambiar("Personaje 2");
        int vida = perso2.getVida();
        int ataque = perso2.getAtaque();
        int nivel = perso2.getNivel();
        int vision = perso2.getVision();
        int movimiento=perso2.getMov();
        boolean dobleAcc = perso2.getDobleAcc();
        boolean evitar = perso2.getEvitar();
        int dobleDano=perso2.dobleDano();  
}
public void Perso3(){
     Personaje3 perso3 = new Personaje3(0,0,0,0,0,false,false,false);
        botones[0][4].Cambiar("Personaje 3");
        int vida = perso3.getVida();
        int ataque = perso3.getAtaque();
        int nivel = perso3.getNivel();
        int vision = perso3.getVision();
        int movimiento=perso3.getMov();
        boolean doblexp = perso3.GetDoblexp();
        boolean arma_ini = perso3.arma_ini();
        boolean dobleCura=perso3.doblcura();  
}
public void mover(){
    int i;
    int j = 0;
    for ( i=0; i<7;i++){
        for ( j=0;j<7;j++){
                
            botones[i][j].addActionListener(new ActionListener() {
          @Override
          public void actionPerformed(ActionEvent e) {
             System.out.println("presionado");

                }   
            });
            if (botones[i][j]==zombi1()){
                if (mover.isSelected()){
                        System.out.println("Selected");
                        botones[i][j].Cambiar("Zombi1");
                        
                    }
                botones[i][j].Cambiar("Zombi1");
                    botones[i][j].addActionListener(new ActionListener() {
              @Override
              public void actionPerformed(ActionEvent e) {
                  System.out.println("posicion==zombi1");

                    }   
                });
                    
                
            }
        }     
    }
     // return botones[i][j];   
}

    // Variables declaration - do not modify                     
    private javax.swing.JButton disparar;
    private javax.swing.JButton jButton4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mover;
    private javax.swing.JButton trepar;
    // End of variables declaration                   


    
}
